### ISSUE TITLE
REPL breaks in recent NodeJS version

### ISSUE THREAD

**Issue by maxlath** [maxlath/lev2#1]
```
./lib/repl.js:28
  const onLine = repl.rli._onLine
                          ^
TypeError: Cannot read properties of undefined (reading '_onLine')
    at module.exports (./lib/repl.js:28:27)
    at init (./lib/index.js:38:16)
    at ./lib/index.js:18:5
    at ReadStream.<anonymous> (./lib/location.js:30:57)
```

`rli` has been removed in v15.0.0, cf https://nodejs.org/api/deprecations.html#DEP0124

I'm not using the REPL much and can't take the time now to update that, but if anyone wants to fix that, you're most welcome

**Comment by maxlath** [comment]
The REPL feature will be removed in `v8.0.0`, as nobody seems to be needing it
